"""initial schema

Revision ID: 0001
Revises: 
"""
import sqlalchemy as sa

import app.security
from alembic import op

revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('at', sa.DateTime(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('actor_role', sa.String(length=20), nullable=True),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('scope', sa.String(length=40), nullable=True),
    sa.Column('allowed', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_actor_id'), ['actor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_at'), ['at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_patient_id'), ['patient_id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('language', sa.String(length=5), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_role'), ['role'], unique=False)

    op.create_table('appointments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('when', sa.DateTime(), nullable=False),
    sa.Column('with_name', sa.String(length=120), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_appointments_patient_id'), ['patient_id'], unique=False)

    op.create_table('consents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('grantee_id', sa.Integer(), nullable=False),
    sa.Column('scopes', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['grantee_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('consents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_consents_grantee_id'), ['grantee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_consents_patient_id'), ['patient_id'], unique=False)

    op.create_table('measurements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=10), nullable=False),
    sa.Column('v1', sa.Float(), nullable=False),
    sa.Column('v2', sa.Float(), nullable=True),
    sa.Column('measured_at', sa.DateTime(), nullable=False),
    sa.Column('source', sa.String(length=10), nullable=False),
    sa.Column('note', app.security.EncryptedText(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('measurements', schema=None) as batch_op:
        batch_op.create_index('ix_meas_patient_kind_at', ['patient_id', 'kind', 'measured_at'], unique=False)

    op.create_table('medications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('prescriber_id', sa.Integer(), nullable=True),
    sa.Column('raw_name', sa.String(length=200), nullable=False),
    sa.Column('product_key', sa.String(length=120), nullable=True),
    sa.Column('generic_name', sa.String(length=200), nullable=True),
    sa.Column('dose_text', app.security.EncryptedText(), nullable=True),
    sa.Column('timing', sa.JSON(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('course_days', sa.Integer(), nullable=True),
    sa.Column('is_antibiotic', sa.Boolean(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('confirmed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('medications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_medications_patient_id'), ['patient_id'], unique=False)

    op.create_table('patient_profiles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('birth_year', sa.Integer(), nullable=True),
    sa.Column('allergies_enc', app.security.EncryptedText(), nullable=True),
    sa.Column('conditions_enc', app.security.EncryptedText(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('refresh_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_refresh_tokens_user_id'), ['user_id'], unique=False)

    op.create_table('screenings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('instrument', sa.String(length=10), nullable=False),
    sa.Column('answers_enc', app.security.EncryptedText(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('band', sa.String(length=30), nullable=False),
    sa.Column('escalated', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('screenings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_screenings_patient_id'), ['patient_id'], unique=False)

    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('assignee_role', sa.String(length=20), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tasks_patient_id'), ['patient_id'], unique=False)

    op.create_table('visit_summaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('content_enc', app.security.EncryptedText(), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('visit_summaries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_visit_summaries_patient_id'), ['patient_id'], unique=False)

    op.create_table('dose_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('medication_id', sa.Integer(), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('slot', sa.String(length=10), nullable=False),
    sa.Column('logged_at', sa.DateTime(), nullable=False),
    sa.Column('source', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['medication_id'], ['medications.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('medication_id', 'day', 'slot')
    )
    with op.batch_alter_table('dose_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dose_logs_patient_id'), ['patient_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dose_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dose_logs_patient_id'))

    op.drop_table('dose_logs')
    with op.batch_alter_table('visit_summaries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_visit_summaries_patient_id'))

    op.drop_table('visit_summaries')
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tasks_patient_id'))

    op.drop_table('tasks')
    with op.batch_alter_table('screenings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_screenings_patient_id'))

    op.drop_table('screenings')
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_user_id'))

    op.drop_table('refresh_tokens')
    op.drop_table('patient_profiles')
    with op.batch_alter_table('medications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_medications_patient_id'))

    op.drop_table('medications')
    with op.batch_alter_table('measurements', schema=None) as batch_op:
        batch_op.drop_index('ix_meas_patient_kind_at')

    op.drop_table('measurements')
    with op.batch_alter_table('consents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_consents_patient_id'))
        batch_op.drop_index(batch_op.f('ix_consents_grantee_id'))

    op.drop_table('consents')
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_appointments_patient_id'))

    op.drop_table('appointments')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_role'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_patient_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_at'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_actor_id'))

    op.drop_table('audit_logs')
    # ### end Alembic commands ###
